algoritmo "SISTEMA DE CRACHÁ DE TÉCNICO"

var

    ntecnino:caractere
    idade:inteiro
    nmaquina:real
    curso:caractere

inicio

    //CABEÇÁRIO
        escreval("_______________________________________________")
        escreval(" ")
        escreval("----------GERADOR DE CRACHÁ DIGITAL------------")
        escreval("_______________________________________________")
        

fimalgoritmo